### ISSUE TITLE
Kodi Matrix 19.0 missing SMB, Web UI in Settings->Services

### ISSUE THREAD

**Issue by bnordgren** [flathub/tv.kodi.Kodi#106]
Upgraded to Matrix from Leia. 

1. My media sources all report "cannot connect to network share". Also, when I try to add a new network source, "SMB" is not on the list of protocols. (And yes, my samba server is running and serving to all comers...including the host on which this flatpak runs.)
2. Settings -> Services -> Control lacks config info for the Web UI. Chorus2 addon is installed and enabled. It's just missing.
3. Settings -> Services -> SMB Client is missing. 

The Settings screen is at the expert level, so nothing should be filtered out, but I cycled through all the settings just in case. These items are just missing.

I'm attempting to downgrade.

**Comment by bnordgren** [comment]
#103 might fix the SMB part.

**Comment by vilmasvensson** [comment]
Does the issue persist with the new release?

**Comment by bnordgren** [comment]
SMB and the Web UI appear in the menus. Chorus2 is accessible on the local network. Everything seems to be working. Thanks!
