### ISSUE TITLE
 Webserver configuration entry missing in Matrix v19.0.0

### ISSUE THREAD

**Issue by topas-rec** [flathub/tv.kodi.Kodi#107]
This is just an additional issue with the already identified dependency problems. I just want to leave it here to let you know that the remote control webserver is also affected.
#103 should fix this since `libmicrohttpd` dependency is added.

There is #101, but I think the webserver is not the problem there.

I don't need help or so just leave it openuntil #103 is closed. (I can help if help is needed)

**Comment by vilmasvensson** [comment]
Could you give an update, since #103 has been merged?

**Comment by topas-rec** [comment]
Tested active commit `7e5f1297d82f` (from flatpak info) in a Debian 10 VM and webserver is there. Seems solved - will report errors on real computer if they exist.

I wanna say thanks for providing my family and me a free (as in free speech) and up to date media center software.
