### ISSUE TITLE
ModuleNotFoundError: No module named PIL

### ISSUE THREAD

**Issue by Rudy96** [flathub/tv.kodi.Kodi#108]
With the Kodi Version 19.0 I get an error when the addon "script.embuary.helper" is used. This addon is nessessary for the skin I use. The error in the log says:

> EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
> NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
> Error Type: <class 'ModuleNotFoundError'>
> Error Contents: No module named 'PIL'
> Traceback (most recent call last):
> File "/home/xxx/.var/app/tv.kodi.Kodi/data/addons/script.embuary.helper/service.py", line 6, in <module> from resources.lib.service_monitor import *
> File "/home/xxx/.var/app/tv.kodi.Kodi/data/addons/script.embuary.helper/resources/lib/service_monitor.py", line 12, in <module> from resources.lib.utils import split
> File "/home/xxx/.var/app/tv.kodi.Kodi/data/addons/script.embuary.helper/resources/lib/utils.py", line 20, in <module> from resources.lib.image import *
> File "/home/xxx/.var/app/tv.kodi.Kodi/data/addons/script.embuary.helper/resources/lib/image.py", line 12, in <module> from PIL import ImageFilter,Image,ImageOps
> ModuleNotFoundError: No module named 'PIL'
> -->End of Python script error report<--

It seems that this issue is similar to #72.

**Comment by woutbr** [comment]
I installed pillow inside the flatpak using your commands and the script.embuary.helper addon doesn't display errors any more.
Thanks!

**Comment by Rudy96** [comment]
Cool. This solution works for me too. Thank you very much.

**Comment by wsnipex** [comment]
this should be fixed with the current v19.1 release
