### ISSUE TITLE
Cannot start kodi. Wayland error.

### ISSUE THREAD

**Issue by greenfoo** [flathub/tv.kodi.Kodi#112]
I haven't run kodi in a few months, and since then many packages have been updated (so I'm not sure whose "fault" it is), but now I get this error when I try to run kodi:
```
$ flatpak run tv.kodi.Kodi
VA error: wayland: Wayland roundtrip error: Protocol error (errno 71)
libva info: VA-API version 1.8.0
libva error: vaGetDriverNameByIndex() failed with invalid VADisplay, driver_name = (null)
terminate called after throwing an instance of 'std::system_error'
  what():  wl_display_roundtrip_queue: Protocol error
/app/bin/kodi: line 182:     7 Aborted                 (core dumped) ${KODI_BINARY} $SAVED_ARGS
Crash report available at /home/zacarias/kodi_crashlog-20210511_000149.log
```

Crash log here: 
[kodi_crashlog-20210510_231020.log](https://github.com/flathub/tv.kodi.Kodi/files/6455226/kodi_crashlog-20210510_231020.log)

**Comment by greenfoo** [comment]
If I had payed more attention to my own bug report I would have noticed that the actual error has nothing to do with VAAPI, but with the wayland connection.

If I force kodi to use X11, everything works again:
```
flatpak run tv.kodi.Kodi --windowing=x11
```

**Comment by yol** [comment]
You might want to jump in here: https://forum.kodi.tv/showthread.php?tid=362520

**Comment by greenfoo** [comment]
Thanks. I'll add more details in that thread.

**Comment by greenfoo** [comment]
As I explain [here](https://forum.kodi.tv/showthread.php?tid=362520&pid=3037565#pid3037565) it turned out to be a problem with my setup and not with the way Kodi is being packed as a flatpak.

Sorry for not having investigated the issue more before opening this ticket.

**Comment by Thesola10** [comment]
If it's still not working on one of your machines, the bug is still very much valid. Flatpak is a sandbox, so it should work regardless of host platform. I think the issue here is that `org.freedesktop.Platform.VAAPI.Intel` has become out-of-date and no longer works on the latest kernel.

**Comment by greenfoo** [comment]
Yes, sorry. I didn't mean it is not a bug :) I meant it is not a **Kodi** issue and that's why I closed this issue (maybe I should open another one in the repository in charge of maintaining the "org.freedesktop.Platform" flatpak package?)

**Comment by Thesola10** [comment]
Flatpak extensions seem to be treated as independent packages, and for some reason the `org.freedesktop.Platform.VAAPI.Intel` repo is archived, meaning it -- and all the apps relying on it -- is stuck on VA-API 1.8 and no further bug reports can be opened.

I'd recommend contacting Flathub or Freedesktop directly.

**Comment by Thesola10** [comment]
> I also noticed a similar bug was filed one year ago (#78) and fixed.

Looking briefly through that bug report, it's not the same. On that past bug, VA-API initializes, and Kodi then fails to create a window. Right now, _nothing remotely Wayland-related is working._ No VA-API, no Kodi, and the relevant error in the log is:

```
2021-05-18 16:38:45.052 T:8     WARNING <general>: wayland-client log message: wl_drm@12: error 0: authenticate failed
```

which is confusingly classified as a warning, but everything afterwards points to repercussions of that authentication problem. Maybe this flatpak is using an outdated Wayland library? (I suspect `waylandpp`)

**Comment by Erick555** [comment]
> Flatpak extensions seem to be treated as independent packages, and for some reason the org.freedesktop.Platform.VAAPI.Intel repo is archived, meaning it -- and all the apps relying on it -- is stuck on VA-API 1.8 and no further bug reports can be opened.

This repo was archived because it's obsolete. VAAPI extension is maintained [here](https://gitlab.com/freedesktop-sdk/freedesktop-sdk).

**Comment by Thesola10** [comment]
@Erick555 As I have stated before, on my tests, VA-API failing on Kodi is only a symptom, not the issue, since the Firefox flatpak which relies on precisely the same VA-API binaries makes use of it successfully under the same Wayland session.

Also please reopen the bug, not everyone has the option to switch away from Intel HD like @greenfoo did.

**Comment by greenfoo** [comment]
Just one clarification: there is an error on that last sentence. In my case...
* The Intel HD laptop works OK.
* The Vega 8 laptop does not.

**Comment by yol** [comment]
> Or actually, the issue might be bigger than just VA-API. As a feature, VA-API is engineered as fail-safe. If it fails to initialize, it doesn't get used and software decoding ensues.

That is not entirely correct as far as the interaction with Wayland is concerned. libva may use a Wayland connection to get the right DRM device and authorize it. If that fails, it is a Wayland protocol error. Wayland protocol errors are always fatal and cause the compositor to close the connection and cut off the entire client. So there is really no "soft fail" here if things are incompatible. As long as a simple `vainfo` is also failing, I don't see how this could be a Kodi-specific issue.

**Comment by Erick555** [comment]
I agree it doesn't look like kodi flatpak issue. Can you show output from `printenv | grep -i libva`?
Also can you try `flatpak run --env=LIBVA_DRIVER_NAME=radeonsi tv.kodi.Kodi`?

**Comment by Thesola10** [comment]
Okay, I managed to run the host's `vainfo` from within the Kodi and Firefox flatpaks, and it would seem that VA-API gets denied if the app isn't already showing a Wayland window. The issue might come from Kodi checking for VA-API _before_ spawning a window.

In both cases, access to `dri` and `wayland` was granted.

**Comment by Thesola10** [comment]
Also, when not provided with a driver, sandboxed VA-API can't even figure out one, giving up with:

```
wl_drm@7: error 0: authenticate failed
VA error: wayland: Wayland roundtrip error: Protocol error (errno 71)
libva info: VA-API version 1.8.0
libva error: vaGetDriverNameByIndex() failed with invalid VADisplay, driver_name = (null)
vaInitialize failed with error code 3 (invalid VADisplay),exit
```

**Comment by Erick555** [comment]
Maybe report that in kodi forum thread where it may get mote attention from kodi developers.

**Comment by yol** [comment]
I'm reading here but still don't see how this is a Kodi issue, unfortunately. `vainfo` should work and if it doesn't, something's broken.

**Comment by Erick555** [comment]
vainfo should work but when it doesn't it shouldn't prevent app from starting which happens only for kodi if I understand this report. For broken vainfo you may look [here](https://github.com/intel/libva/issues/278).

**Comment by Thesola10** [comment]
well, I'm on Intel HD... `radeonsi` is kind of entirely irrelevant to me

**Comment by yol** [comment]
@Erick555 As said, Wayland protocol errors are always fatal. We don't really have a choice as far as I can tell.

**Comment by Erick555** [comment]
@Thesola10 the thread I linked contains reports from both Intel and AMD gpu owners (the first comment mentions intel so I don't know how you made conclusion it's irrelevant. The OP in the thread here have issues on AMD so if you think you have different issue then you should open new thread for discussion.

@yol is every single flatpak app crashing with Wayland protocol errors or only kodi? The comment from https://github.com/flathub/tv.kodi.Kodi/issues/112#issuecomment-846036056 suggest it's kodi specific behaviur to call vaapi before it spawn any window which leads to crash in wayland. If this happens for every app then it's wrong place to discuss it here.

**Comment by yol** [comment]
> Okay, I managed to run the host's vainfo from within the Kodi and Firefox flatpaks, and it would seem that VA-API gets denied if the app isn't already showing a Wayland window.

@Thesola10 You mean you can open *any* unrelated window with another command and then it will work or how did you test?

@Erick555 AFAIK, there is no requirement to create a Wayland window before initializing vaapi, so Kodi is doing nothing "wrong" (note that vainfo doesn't create a window at all because it would make no sense). Also and more importantly, I'm not quite sure yet what the *actual* issue is since, clearly, the Flatpak is also working for some (or most?) people on both Intel and AMD, including me. So either this is something else entirely or a requirement that only exists in certain versions or distributions of Flatpak? All in all, I just haven't been able to reproduce and this looks like a problem that requires a good debugging session and is hard to solve via telediagnosis :/

**Comment by Thesola10** [comment]
@yol `vainfo` works fine outside of the flatpak sandbox. It fails inside flatpak, regardless of whether I'm in Firefox or Kodi's flatpak. Firefox loads VA-API after showing a window and it works. Kodi loads VA-API before showing a window and it doesn't work. `vainfo` doesn't open a window and it doesn't work. It looks to me like the Wayland proxy on my Flatpak install is being picky about what to authorize. Has to be the same process, opening a window and `vainfo` in the same sandbox independently doesn't solve it.

Seems like I've inadvertently ended up in quite the conundrum, but I have no idea how to configure or clear state for `bwrap`...

**Comment by yol** [comment]
@Thesola10 Hmm, to be honest that sounds like it *could* be related to a window but it *could* also be totally unrelated :/ Only way to check this would be if you recompiled Kodi and fumbled in a vaapi check after the window creation.

> It looks to me like the Wayland proxy on my Flatpak install is being picky about what to authorize. 

To the extent of my knowledge, Flatpak does not proxy Wayland. It only proxies dbus if so configured.

**Comment by Thesola10** [comment]
Okay, found the issue: turns out `LD_LIBRARY_PATH=/run/host/lib LIBVA_DRIVERS_PATH=/run/host/lib/dri /run/host/lib/ld-2.33.so /run/host/bin/vainfo` works perfectly from within flatpak. It's just that the version of VA-API shipped with flatpak is ancient and breaks on latest kernel.

**Comment by Thesola10** [comment]
Update: anything but the latest VA-API fails, even Nix's 1.10 crashes the exact same way (Kodi or `vainfo`), only my host 1.11 works...

**Comment by yol** [comment]
It's probably https://github.com/intel/libva/pull/476 - which means the only problem really is that libva is too old and broken

**Comment by Erick555** [comment]
Runtime issues should be reported at https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues There is no similar issue opened currently.

Flatpak runtime contains [libva 2.8.0](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/release/20.08/elements/components/libva.bst#L36) released 1 year ago so it's not ancient but not the latest either. Keep in mind that updating libva may be impossible due to abi stability constraints but backporting specific patches may be doable

**Comment by achimfrase** [comment]
I have opened a report at freedesktop-sdk
[https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1252](url) :+1:

**Comment by greenfoo** [comment]
@achimfrase the "href" of your link above points to "url", which resolves to `<current_page>/url --> <current_page>`. I was really confused when I clicked on your link from my email client :)

**Comment by Erick555** [comment]
The fix was [merged in git](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/merge_requests/5069). Should be released soon to flathub.

**Comment by rijnhard** [comment]
Likely related ticket on ubuntu
https://bugs.launchpad.net/ubuntu/+source/libva/+bug/1961484

**Comment by razzeee** [comment]
Manjaro unstable on wayland still seems fine
