### ISSUE TITLE
some codecs missing?  how to solve this issue?

### ISSUE THREAD

**Issue by dreamcat4** [flathub/tv.kodi.Kodi#114]
Hey there,

I used to use kodi installed via APT. However after upgrading my ubuntu installation to 21.04 it somehow also upgraded kodi and then that broke dependencies which then broke scripts and addons and python things.

So to help solve my problem, i installed this flatpak here from flathub. Great! My kodi install works again right?

Well the python is fixed. However the first launch it spammed a whole bunch of messages at me. Which was totally unnecessary and tedious from a user point of view. Very unprofessional looking. Nevertheless things seem overall less bkoken now than before.

Only problem is... some codecs are missing. I know this because before moving to flatpak certain videos would playback just fine in kodi. But now I only get the audio and the video is gone. Back screen.

Here is an example video, one of my favorites:

https://www.youtube.com/watch?v=gkTb9GP9lVI

Can you guys play it? Does that one work for any of you?

Is there some way i can use flatseak to add any extra premonitions for folder access for a folder on my root filesystem? Something like to mount the /var/lib/ folder where the missing codecs lives? That would be helpful.

Otherwise you have packs to sideload the missing codecs? Because that would also be ok by me. I just cannot find any existing instructions anywhere for how to do that.

Much help appreciated, and I do hope you enjoy the song. Even if audio only, (but that really is missing the best part of it, hehe).

**Comment by BlobCodes** [comment]
I also have the same issue - my library is mostly in the AV1 codec, which this flatpak does not seem to support. YouTube also now seems to encode all videos above ~100.000 views to AV1.
I think it could have something to do with the packaged version of ffmpeg.

btw why does this flatpak even provide its own version of ffmpeg and not just use the ffmpeg-full extension?

**Comment by razzeee** [comment]
Can you please check again, this seems like it should be fixed.
