### ISSUE TITLE
Freedesktop SDK 19.08 runtime is no longer supported as of September 1, 2021.

### ISSUE THREAD

**Issue by nicrame** [flathub/tv.kodi.Kodi#117]
Hello.
When i was running flatpak update last day i got this information:
Informacja: org.freedesktop.Platform jest niewspierane z powodu: The Freedesktop SDK 19.08 runtime is no longer supported as of September 1, 2021. Please ask your application developer to migrate to a supported version
Informacja: org.freedesktop.Platform.VAAPI.Intel jest niewspierane z powodu: The Freedesktop SDK 19.08 runtime is no longer supported as of September 1, 2021. Please ask your application developer to migrate to a supported version
Informacja: org.freedesktop.Platform.Locale jest niewspierane z powodu: The Freedesktop SDK 19.08 runtime is no longer supported as of September 1, 2021. Please ask your application developer to migrate to a supported version
Informacja: org.freedesktop.Platform.GL.default jest niewspierane z powodu: The Freedesktop SDK 19.08 runtime is no longer supported as of September 1, 2021. Please ask your application developer to migrate to a supported version

Those are Kodi flatpak dependencies. I think this is also good occasion to fix neverending issue with missing nmblookup in flatpak Kodi ( https://github.com/flathub/tv.kodi.Kodi/issues/71 ).

**Comment by Erick555** [comment]
> Those are Kodi flatpak dependencies

They aren't. Kodi uses [Freedesktop SDK 20.08](https://github.com/flathub/tv.kodi.Kodi/blob/master/tv.kodi.Kodi.yml#L3). Your problem isn't related to kodi.

**Comment by nicrame** [comment]
> 
> 
> > Those are Kodi flatpak dependencies
> 
> They aren't. Kodi uses [Freedesktop SDK 20.08](https://github.com/flathub/tv.kodi.Kodi/blob/master/tv.kodi.Kodi.yml#L3). Your problem isn't related to kodi.

You are right. It had to be some older version, and flatpak just leaving old dependencies installed when removing/upgrading apps.
```
# flatpak uninstall --unused
        Identyfikator                                 Gałąź          Dz
 1. [-] org.freedesktop.Platform.GL.default           19.08          r
 2. [-] org.freedesktop.Platform.VAAPI.Intel          19.08          r
 3. [-] org.freedesktop.Platform                      19.08          r
 4. [-] org.freedesktop.Platform.Locale               19.08          r

```
