### ISSUE TITLE
Can't use external player

### ISSUE THREAD

**Issue by Solarunit** [flathub/tv.kodi.Kodi#122]
Is there a way to use an [external player](https://kodi.wiki/view/External_players) i.e. mpv in Kodi **flatpak** version?

When using a normal Kodi version you need to add this  in the `~/.kodi/userdata/playercorefactory.xml` 

```
<playercorefactory>
  <players>
    <player name="MPV" type="ExternalPlayer" audio="false" video="true">
      <filename>/usr/bin/mpv</filename>
      <args>--fs=yes "{1}"</args>
      <hidexbmc>false</hidexbmc>
    </player>
  </players>
  <rules action="prepend">
    <rule video="true" player="MPV"/>
  </rules>
</playercorefactory>

```

So I copied file to the flatpak location:

`~/.var/app/tv.kodi.Kodi/data/userdata/playercorefactory.xml`

And it doesn't work:

`sh: line 1: /usr/bin/mpv: No such file or directory`

I have also tried to enable additional permissions via Flatseal app, same result.

**Comment by Solarunit** [comment]
> flatpak sandboxes applications, so you can't simply access stuff outside of it's own files. 

I assume flatpak app also can't "talk" with other flatpak app (mpv)

>Likely the external player would have to be part of the kodi flatpak

I think it very unlikely going to happen.

> or accessible via a portal

Is it possible to do it today? How? Or we need to wait for the flatpak update with this feature?

**Comment by wsnipex** [comment]
no, it's not possible afaik, but I'm no flatpak expert
