### ISSUE TITLE
Support AV1 Codec

### ISSUE THREAD

**Issue by BlobCodes** [flathub/tv.kodi.Kodi#126]
Part of #114 ?

This version of kodi does not seem to be able to play AV1-encoded videos.
That's particularly important because YouTube nowadays encodes a lot of its videos in AV1.

**Comment by wsnipex** [comment]
please test the proposed fix linked above

**Comment by BlobCodes** [comment]
The fix above does not work. The audio plays, but the background seems to be transparent.
Below is a screenshot of me playing a AV1 video while opening the statistics for nerds. It shows that the ff-av1 decoder is used (sorry for it being german)

![Bildschirmfoto vom 2021-11-16 16-44-22](https://user-images.githubusercontent.com/14961554/142017772-28707a72-4328-4767-84dc-8d8875db3056.png)

**Comment by BlobCodes** [comment]
I just found out that I accidentally started the stable version of kodi.
@wsnipex your fix does actually work!
