### ISSUE TITLE
AC3 transcoding broken with FFmpeg 4.4

### ISSUE THREAD

**Issue by toupeira** [flathub/tv.kodi.Kodi#127]
The latest update broke AC3 transcoding for me, so for example with AAC tracks I don't get any audio output.

This is probably caused by the switch to FFmpeg 4.4 in https://github.com/flathub/tv.kodi.Kodi/commit/8daa5ba82fc36ac90d1af4d3b9e609ddf935cca3, because I just recently [encountered the same problem with the Debian package](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=993806) and figured I'd switch to the Flatpak to work around this :sweat_smile: 

[There's a fix in Kodi 20.x](https://github.com/xbmc/xbmc/pull/19558) but backporting seems tricky.

Could the Flatpak maybe revert to FFmpeg 4.3 for now?

### Workaround

I was able to downgrade to the previous version with:

```sh
sudo flatpak update --commit=0670d916732866f75a7df4ef50a6e07a3ba05beda445294e90b8df6043bb928a tv.kodi.Kodi
```

**Comment by wsnipex** [comment]
Meh, ffmpeg should never have been bumped past 4.3 for kodi v19
@Marko10-000 ping

**Comment by wsnipex** [comment]
please test the PR above

**Comment by toupeira** [comment]
@wsnipex thanks, I tested the build from https://github.com/flathub/tv.kodi.Kodi/pull/128#issuecomment-970316094 and AC3 transcoding is working again! :+1:

**Comment by Marko10-000** [comment]
@wsnipex Why shouldn't we bump to a higher minor version of ffmpeg? It could patch problems. I made (and tested it with an example ac3 file) a patch https://github.com/Marko10-000/tv.kodi.Kodi/tree/beta. The main change was to enable the decoders. Changes can be seen here https://github.com/Marko10-000/tv.kodi.Kodi/commit/afdbc8bbf20f24b3e82db5b51d217962456fbba7. Perhaps we could add your av1 support?

**Comment by toupeira** [comment]
@Marko10-000 I don't know the details, but FFmpeg 4.4 seems to contain some breaking changes which were ony fixed with https://github.com/xbmc/xbmc/pull/19558 in Kodi 20.x.

Note that the problem I encountered is only with AC3 *transcoding* (from e.g. AAC), actual AC3 sources still worked fine for me with the faulty version.

**Comment by wsnipex** [comment]
@Marko10-000 because we support only ffmpeg 4.3 for kodi 19. There are breaking changes in 4.4, as has already been pointed out.

**Comment by wsnipex** [comment]
fixed
