### ISSUE TITLE
wayland executable?

### ISSUE THREAD

**Issue by achimfrase** [flathub/tv.kodi.Kodi#13]
Is there a wayland executable? Or is wayland support disabled at the moment for the Flatpak version of Kodi? Regards, Achim

**Comment by comparascope** [comment]
Not available. See this thread: 

https://github.com/flathub/flathub/pull/673#issuecomment-429894353

Unsure what we will do about it in future.

**Comment by achimfrase** [comment]
> Not available. See this thread:
> 
> [flathub/flathub#673 (comment)](https://github.com/flathub/flathub/pull/673#issuecomment-429894353)
> 
> Unsure what we will do about it in future.

Okay, Thanks for your quick replay.
I hope there is going to be a solution in the near future.

**Comment by achimfrase** [comment]
That are great news!

**Comment by achimfrase** [comment]
Yes it is working! Thanks a lot for your hard work!
