### ISSUE TITLE
On fedora 35 kinoite (kde version of silverblue) the Music and the Pictures directory are not accessible

### ISSUE THREAD

**Issue by RobVerduijn** [flathub/tv.kodi.Kodi#133]
Hello,

When running kodi flatpak on kinoite 35 (the kde version of fedora silverblue) 
The folders ~/Music and ~/Pictures cannot be read by kodi.
The folder ~/Videos however works fine.

kinoit can be found here: [download](https://kinoite.fedoraproject.org/download/)

What could be causing this ?

Rob

**Comment by Erick555** [comment]
You may check content of `~/.config/user-dirs.dirs` if XDG variables point to right paths.

**Comment by nicrame** [comment]
> Hello,
> 
> When running kodi flatpak on kinoite 35 (the kde version of fedora silverblue) The folders ~/Music and ~/Pictures cannot be read by kodi. The folder ~/Videos however works fine.
> 
> kinoit can be found here: [download](https://kinoite.fedoraproject.org/download/)
> 
> What could be causing this ?
> 
> Rob

Check if Your Kodi flatpak have access to those folders.
You may use Flatseal for that (flatpak install Flatseal -y).

**Comment by RobVerduijn** [comment]
Hi,
Sorry ppl,
RL got in the way and I completely forgot posting the solution to my problem.
@Erick555 was spot on, the ~/.config/user-dirs.dirs had some faulty entries.

it was

```
XDG_DESKTOP_DIR="$HOME/Desktop"
XDG_DOWNLOAD_DIR="$HOME/Downloads"
XDG_TEMPLATES_DIR="$HOME/Templates"
XDG_PUBLICSHARE_DIR="$HOME/Public"
XDG_DOCUMENTS_DIR="$HOME/Documents"
XDG_MUSIC_DIR="$HOME/"
XDG_PICTURES_DIR="$HOME/"
XDG_VIDEOS_DIR="$HOME/Videos"
```

Then set it to

```
XDG_DESKTOP_DIR="$HOME/Desktop"
XDG_DOWNLOAD_DIR="$HOME/Downloads"
XDG_TEMPLATES_DIR="$HOME/Templates"
XDG_PUBLICSHARE_DIR="$HOME/Public"
XDG_DOCUMENTS_DIR="$HOME/Documents"
XDG_MUSIC_DIR="$HOME/Music"
XDG_PICTURES_DIR="$HOME/Pictures"
XDG_VIDEOS_DIR="$HOME/Videos"
```

@nicrame didn't know flatseal.... that is a usefull tool for debugging...I'll keep it in mind

Cheers
Rob
