### ISSUE TITLE
Just updated and Kodi 20 alpha was installed...

### ISSUE THREAD

**Issue by cgcgcgcgcg** [flathub/tv.kodi.Kodi#135]
I did a "flatpak update tv.kodi.Kodi" and Nexus screen greeted me.
Obviously something is wrong.
How can I go back to Kodi v19.3?
![k_20211221-092647](https://user-images.githubusercontent.com/38960370/146889733-8f25d549-f094-45a7-a633-6e3cba838cc0.png)

**Comment by cgcgcgcgcg** [comment]
I tried removing everything with:
flatpak remove org.freedesktop.Platform.openh264 org.freedesktop.Platform.GL.default org.freedesktop.Platform tv.kodi.Kodi

Then installed with:
flatpak install flathub tv.kodi.Kodi

But Kodi Nexus alpha is installed.

**Comment by razzeee** [comment]
It seems like I mixed up the beta and master branch :confused:

**Comment by Erick555** [comment]
@razeee shouldn't this be reverted or reverting this can break config?

**Comment by cgcgcgcgcg** [comment]
> @razeee @wsnipex shouldn't this be reverted or reverting this can break config?
> 
> EDIT: actually was there a force-push?

I tried deleting everything and installing Kodi (like above), and Nexus is still installed.
![k_20211221-172014](https://user-images.githubusercontent.com/38960370/146954414-0610c2f0-e45a-470b-9a85-afe4f1715965.png)

**Comment by razzeee** [comment]
Yes, we force pushed to fix it. As that should have worked fine according to a flathub admin. I even started a stable build by hand on the build infra, but something seems wrong. Atm I'm not sure why it didn't work. One path we're exploring is having https://github.com/flathub/tv.kodi.Kodi/pull/137 and hopefully just having it fixed due to that.

**Comment by Erick555** [comment]
The new (old) stable release is published so `flatpak update` should fix this for everyone affected and this can be closed.

**Comment by cgcgcgcgcg** [comment]
> The new (old) stable release is published so `flatpak update` should fix this for everyone affected and this can be closed.

Thank you for the fast fix.

**Comment by Shoegzer** [comment]
Just updated via flatpak update and even though it's now showing the proper version, IPTV is no longer showing anything as it was prior to yesterday's update.  Verified the IPTV settings are intact.

**Comment by razzeee** [comment]
@Shoegzer can you try to roll back and see if it's actually broken by the update? 
See https://unix.stackexchange.com/questions/552688/is-it-possible-to-roll-back-a-flatpak-update

**Comment by Shoegzer** [comment]
Thanks @razzeee. Rolled back to commit `2d65bf10c627a44d447e9b4da96592e535ebfbbe62e72945ca1abfc3a3e4efd0` from 17 November, which was working before but now it's not.  

Also, upon updating I noticed the following message in terminal, not sure if it's related:

```
Note that '/var/lib/flatpak/exports/share' is not in the search path
set by the XDG_DATA_HOME and XDG_DATA_DIRS
environment variables, so applications may not
be able to find it until you set them. The
directories currently searched are:

- /root/.local/share
```
Would starting from a fresh config help?  If so, what's the recommended method in this case?

**Comment by razzeee** [comment]
Wouldn't think that it would help. Posting an the actual kodi.log of an attempt might show what's happening

**Comment by Shoegzer** [comment]
Actually this was a misconfiguration on this end which was fixed.  Seems to be working fine now, but thanks for your help.
