### ISSUE TITLE
tv.kodi.Kodi uses python v3.9 while Kodi still uses v3.8 general issue with addons

### ISSUE THREAD

**Issue by cg00001** [flathub/tv.kodi.Kodi#163]
Flatpak Kodi is way better than using system Kodi on Arch (python v3.10.4-1) where it's always crashing, but some addons refuse to work in Flatpak Kodi because methods and classes are deprecated in v3.9, while still work in v3.8.

Like the unescape() method. Last one here:
https://docs.python.org/3/whatsnew/3.9.html#removed

I wonder if Kodi devs will ever make system Kodi work with current python versions, since it's clearly faster.

**Comment by Erick555** [comment]
I guess it may be better to ask in [kodi repo](https://github.com/xbmc/xbmc/issues) as this one is flatpak packaging.

**Comment by razzeee** [comment]
As we're now on v20, this might have chnaged.
