### ISSUE TITLE
Timezone settings are ignored

### ISSUE THREAD

**Issue by linuxissuper** [flathub/tv.kodi.Kodi#165]
Kodi flatpak seems to always use UTC but the system time is set to CEST   
I also tried to change the regional settings in Interface, but all the timezone settings don't change anything  
```
timedatectl status
               Local time: Fri 2022-06-17 12:48:44 CEST
           Universal time: Fri 2022-06-17 10:48:44 UTC
                 RTC time: Fri 2022-06-17 10:48:44
                Time zone: Europe/Amsterdam (CEST, +0200)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no
 ```  
Kodi always shows Universal time  
  
I'm on NixOS and when I try the nixos kodi package, everything works  
and the timezone settings in kodi also get applied

**Comment by Erick555** [comment]
It may be generic flatpak issue with nixos. Does the timezone is set correctly in any other flatpak?

**Comment by linuxissuper** [comment]
I've installed `si.tano.Vremenar` and `org.gnome.Weather` but both cannot even connect to display...   
Probably something isn't right with my system or with flatpak on NixOS  
Have to look into it, what I might be doing wrong

**Comment by linuxissuper** [comment]
I've tried the flatpak kodi package on another system and it works   
Definitely something with my system or NixOS in general
