### ISSUE TITLE
Is there a way in Linux to have multiple different Kodis than this

### ISSUE THREAD

**Issue by cg00001** [flathub/tv.kodi.Kodi#168]
I simply rename the data folder ~/.var/app/tv.kodi.Kodi/data to eg data1 after messing with one Kodi, start Kodi again and it creates a new data folder for me to play.
If I use 3 for example and want to use the middle one, I just rename eg data2 to data.
Is there a better way?
My scripting abilities are not so good so I can create one that has for example 4 selections and automates the renaming.

**Comment by razzeee** [comment]
I don't think you can. At least not without rebuilding the whole app.

**Comment by cg00001** [comment]
> I don't think you can. At least not without rebuilding the whole app.

Think of a menu like this on a bash script:
Select Kodi version (1-5)
1 Arctic Horizon 2 with 4 addons
2 Titan M O D with 6 addons
3 Madnox with 5 addons
4 Cosmic with 7 addons
5 Testing
6 Set current data folder to default

This (if I could implement it) would just rename the appropriate Kodi data folder (eg data2) to data, so clicking on the Flatpak Kodi link -I could easily make it run too- would load that specific one.
Last command would rename eg data to data2.

**Comment by razzeee** [comment]
Yeah, you can move the folders fine. I wouldn't say that that's "multiple Kodis" but it seems to fit your needs.

**Comment by cg00001** [comment]
> Yeah, you can move the folders fine. I wouldn't say that that's "multiple Kodis" but it seems to fit your needs.

I'm a bit rusty on bash, but I figured out a way, and looking at Zenity for looks.

**Comment by wsnipex** [comment]
It should (c) be possible to override KODI_HOME if we use some other var then XDG_DATA_HOME here: https://github.com/flathub/tv.kodi.Kodi/blob/master/kodi.sh.in.patch#L10

Flatpak insist on overriding $XDG_DATA_HOME, so you're not able to set it to anything else then ~/.var/app/tv.kodi.Kodi/data

**Comment by cg00001** [comment]
> It should (c) be possible to override KODI_HOME if we use some other var then XDG_DATA_HOME here: https://github.com/flathub/tv.kodi.Kodi/blob/master/kodi.sh.in.patch#L10
> 
> Flatpak insist on overriding $XDG_DATA_HOME, so you're not able to set it to anything else then ~/.var/app/tv.kodi.Kodi/data

Yes, I noticed, lol. Using Yad I'm having progress making a simple Kodi launcher for my needs.
A simple shortcut is enough to execute FlatPak Kodi from Yad when renaming is done:
/var/lib/flatpak/exports/bin/tv.kodi.Kodi

**Comment by cg00001** [comment]
OK, here it is for the few that may need it, it needs just yad and thunar. Set it as executable so clicking on it is enough: chmod +x Kodi.Launcher.sh
How it works:
First option opens your Flatpak folder containing your "builds", so you can see if the data folder exists, and remember what build it is (if not just run Kodi from the last option to see).
The next 6 options rename data folder to preset names (see script) , so you can run another build -all mv commands used with -n so no overwriting is done, ever.
The next 6 options rename again a build to data, so you can click the last button and run Kodi.
![Kodi Launcher](https://user-images.githubusercontent.com/38960370/182720582-e145d2a9-3edc-4019-9445-f340e3c7733d.png)

Script:
`#!/bin/bash
# made by cg

yad --title "Flatpak Kodi Multiple Builds Launcher" --form --width=500 --height=600 --text="<b>Select an option</b>" --image "dialog-question" --image-on-top \
--field "<b>Check your</b> existing builds":fbtn "thunar $HOME/.var/app/tv.kodi.Kodi/" \
--field="<b>data to</b> Build number 1":fbtn "/usr/bin/mv -n $HOME/.var/app/tv.kodi.Kodi/data $HOME/.var/app/tv.kodi.Kodi/dataM" \
--field="<b>data to</b> Build number 2":fbtn "/usr/bin/mv -n $HOME/.var/app/tv.kodi.Kodi/data $HOME/.var/app/tv.kodi.Kodi/dataX" \
--field="<b>data to</b> Build number 3":fbtn "/usr/bin/mv -n $HOME/.var/app/tv.kodi.Kodi/data $HOME/.var/app/tv.kodi.Kodi/dataXF" \
--field="<b>data to</b> Build number 4":fbtn "/usr/bin/mv -n $HOME/.var/app/tv.kodi.Kodi/data $HOME/.var/app/tv.kodi.Kodi/dataD" \
--field="<b>data to</b> Build number 5":fbtn "/usr/bin/mv -n $HOME/.var/app/tv.kodi.Kodi/data $HOME/.var/app/tv.kodi.Kodi/dataE" \
--field="<b>data to</b> Build number 6":fbtn "/usr/bin/mv -n $HOME/.var/app/tv.kodi.Kodi/data $HOME/.var/app/tv.kodi.Kodi/dataXL" \
--field="<b>Build number 1 to</b> data":fbtn "/usr/bin/mv -n $HOME/.var/app/tv.kodi.Kodi/dataM $HOME/.var/app/tv.kodi.Kodi/data" \
--field="<b>Build number 2 to</b> data":fbtn "/usr/bin/mv -n $HOME/.var/app/tv.kodi.Kodi/dataX $HOME/.var/app/tv.kodi.Kodi/data" \
--field="<b>Build number 3 to</b> data":fbtn "/usr/bin/mv -n $HOME/.var/app/tv.kodi.Kodi/dataXF $HOME/.var/app/tv.kodi.Kodi/data" \
--field="<b>Build number 4 to</b> data":fbtn "/usr/bin/mv -n $HOME/.var/app/tv.kodi.Kodi/dataD $HOME/.var/app/tv.kodi.Kodi/data" \
--field="<b>Build number 5 to</b> data":fbtn "/usr/bin/mv -n $HOME/.var/app/tv.kodi.Kodi/dataE $HOME/.var/app/tv.kodi.Kodi/data" \
--field="<b>Build number 6 to</b> data":fbtn "/usr/bin/mv -n $HOME/.var/app/tv.kodi.Kodi/dataXL $HOME/.var/app/tv.kodi.Kodi/data" \
--field="<b>Run Flatpak Kodi</b> now":fbtn "/var/lib/flatpak/exports/bin/tv.kodi.Kodi" \
--button=yad-ok:0`
