### ISSUE TITLE
tv.kodi.Kodi not found in flathub repository

### ISSUE THREAD

**Issue by mitvjw** [flathub/tv.kodi.Kodi#171]
SP:
He instalado FLATPAK en una Raspberry 400 con RASPBERRY OS 64bit completamente actualizado (Debian 11 Bullseye) siguiendo la guía de instalación y, al instalar KODI (flatpak install tv.kodi.Kodi) obtengo un mensaje que indica que no encuentra tal aplicación en el repositorio:
error: No se encontraron referencias similares a <<tv.kodi.Kodi>>.
He buscado y no he encontrado nada al respecto.
¿Pueden ayudarme?
¿FlatPak sigue ofreciendo KODI o lo ha eliminado? ¿Hay algún otro repositorio? ¿Hay algún error en el repositorio?
Muchas gracias.

ENG:
I've installed FLATPAK on a Raspberry 400 running Raspberry OS 64bIt fully updated (Debian 11 Bullseye) following the "setup guide", and, when trying to install KODI (command "flatpak install tv.kodi.Kodi) I recieve an error stating that this application is not found in this repository:
NOT FOUND SIMILAR REFERENCES TO <<tv.kodi.Kodi>>
Can you help me?
Thanks.

**Comment by Erick555** [comment]
Flatpak kodi is for x86 only

**Comment by mitvjw** [comment]
It's really difficult to be aware of the fact that kodi flatpak is not available for Raspberry.
I had read it was available for this platform.
And even once you know it's not avaiblable, trying to get the information is not easy:

> [README.MD](https://github.com/flathub/tv.kodi.Kodi/blob/master/README.md)
where it is readable that <<Available as a native application for Android, Linux, BSD, macOS, iOS, tvOS and Windows operating systems, Kodi runs on most common processor architectures. This repository packages it through Flatpak>>

FLATPAK webpage for every application SHOULD detail platforms for wich it is available.
Too much time wasted trying to get it.

THANK YOU very much for your help.
