### ISSUE TITLE
HW decoding

### ISSUE THREAD

**Issue by G-Ray** [flathub/tv.kodi.Kodi#18]
Thanks for this amazing work!

In Kodi settings, there is no way to enable/disable va-api or other HW decoding API.
Is there any technical limit to enable this ?

**Comment by Marko10-000** [comment]
Please ask the Kodi support https://forum.kodi.tv/

**Comment by G-Ray** [comment]
Maybe you did not understand my request:

In this flatpak, there is no options regarding HW decoding, meanwhile these options are available in other kodi builds (https://rpmfusion.org for instance). I guess Kodi is compiled without nedded flag(s) for HW decoding support.

HW decoding is important, particularly to decode 2160p videos, so this issue would request support for hardware decoding in this build.

**Comment by wsnipex** [comment]
confirmed, kodi fails to load the vaapi driver:
OS: ubuntu 18.04
> libva info: VA-API version 1.1.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: va_openDriver() returns -1

you can work around it by creating the following symlink:

>cd  /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/18.08/active/files/lib/x86_64-linux-gnu/dri
sudo ln -s intel-vaapi-driver/i965_drv_video.so

this will create a **dangling symlink**. (I assume)Flatpack mounts the vaapi driver from org.freedesktop.Platform.VAAPI.Intel there at runtime, so it works (for me).

@nedrichards @TingPing  this looks like a framework bug

**Comment by TingPing** [comment]
Should be reported here: https://gitlab.com/freedesktop-sdk/freedesktop-sdk

Should be a simple bug.

**Comment by tilosp** [comment]
Looks like it's already fixed: https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues/463
But it's not yet updated on flathub.

**Comment by TingPing** [comment]
Current rate seems to be about 1 release per week.

**Comment by nedrichards** [comment]
Yeah - this is literally the issue I was asking if we should hold the release of kodi on flathub for ;-) the FDo SDK people are very friendly and easy to chat to in #freedesktop-sdk on freenode if you have questions about when the release is pushed to flathub.

**Comment by TingPing** [comment]
Last I heard they planned on it this Friday.

**Comment by Erick555** [comment]
New freedesktop release is on flathub thus this should be fixed now.

**Comment by G-Ray** [comment]
It works Perfectly now, I close this
