### ISSUE TITLE
Airplay support

### ISSUE THREAD

**Issue by Grokafar** [flathub/tv.kodi.Kodi#186]
Hi !
I recently installed Kodi from flatpak (thanks for your work!) and I noticed that Airplay is not supported on the flatpak version despite of the support in the main version.

Is it planned to add this ?

**Comment by razzeee** [comment]
I have never used airplay or know anything about it, so I wouldn't even know where to start looking :/

**Comment by FeelTheLemon** [comment]
From [this page ](https://kodi.wiki/view/AirPlay) it looks like kodi just should have access to avahi daemon in host system.

**Comment by razzeee** [comment]
Can you try adding `"--system-talk-name=org.freedesktop.Avahi"` via FlatSeal and let us know if Airplay then works?

**Comment by Grokafar** [comment]
Hello thanks for your reponses. I can see that org.freedesktop.Avahi is already set. Also it seems to be present here: https://github.com/flathub/tv.kodi.Kodi/blob/master/tv.kodi.Kodi.yml#L25

In the interface I can't see Service > Airplay as mentioned in the documentation.

According to the documentation https://kodi.wiki/view/AirPlay, Kodi seems to use shairplay software to support Airplay. Maybe it is possible to add it as a dependencies to the Flat app ?

**Comment by razzeee** [comment]
I guess we would need to build it like remmina does here https://github.com/flathub/org.remmina.Remmina/blob/3215b5c6eccefade61d95e6b5a17501c48c9c83c/org.remmina.Remmina.json#L173

**Comment by Grokafar** [comment]
Amazing Airplay works like a charm :) 

Thanks guys !
