### ISSUE TITLE
python version

### ISSUE THREAD

**Issue by unicornsandcandies** [flathub/tv.kodi.Kodi#188]
Addons refuse to work with new python version. Can we have 3.8? It's there any workaround or something. It's affecting addons that my whole Kodi build is based on.

**Comment by wsnipex** [comment]
debuglog?

**Comment by unicornsandcandies** [comment]
https://github.com/trakt/script.trakt/issues/604

**Comment by razzeee** [comment]
The flatpak should have 3.10.6, so if https://github.com/trakt/script.trakt/issues/586#issuecomment-1079977338 is right it shouldn't happen or python regressed...

**Comment by razzeee** [comment]
Are you still seeing this with v20?
