### ISSUE TITLE
Include (some) visualisation plugins?

### ISSUE THREAD

**Issue by DamageIncorporated** [flathub/tv.kodi.Kodi#189]
I know this would add bloat to the flatpak, but I don't see any option for me to get these (or any binary) addons on the SteamDeck's SteamOS without messing with the write protection of the System: 

While one can install regular packages, these will be overwritten on every OS update, which is a route I don't want to go down. The steam deck is meant as an appliance after all...

**Comment by razzeee** [comment]
I'm not sure what you mean, the flatpak has (some) visualisations already https://github.com/flathub/tv.kodi.Kodi/blob/master/tv.kodi.Kodi.yml#L225
