### ISSUE TITLE
Looking for Arch lib packages to open issues about crashing in Flatpak.

### ISSUE THREAD

**Issue by cg00001** [flathub/tv.kodi.Kodi#191]
The logs and description are in: https://github.com/xbmc/xbmc/issues/22213
The PVR fix doesn't work for me.

**Comment by razzeee** [comment]
Or when it starts https://github.com/flathub/tv.kodi.Kodi/issues/188

**Comment by cg00001** [comment]
@razzeee PVR IPTV Simple Client isn't enabled on the test data folders I use.
Arch python version is current: 3.10.8-3

**Comment by cg00001** [comment]
> Arch python version is irrelevant, as the flatpak brings it's own version.

I know but I thought in the recommended issues they used that to specify Flatpak package or something.

**Comment by cg00001** [comment]
@razzeee Last time I checked Flatpak's python was 3.9, sincerely I don't remember how to check what the current one is.

**Comment by razzeee** [comment]
![image](https://user-images.githubusercontent.com/5943908/206525801-9768b1e4-e1d6-40ae-9351-d04c4b592316.png)

**Comment by cg00001** [comment]
Can anyone look at my logs in https://github.com/xbmc/xbmc/issues/22213 and tell me what Arch packages are to blame for this so I can open issue(s) where I should?

**Comment by cg00001** [comment]
The issue is not coming from my desktop.
I have an old laptop where Kodi worked -I haven't updated its Arch for a very long time.
I did a full update today and all symptoms from the desktop appeared.
Crashing, skin settings buttons don't work at all -they did before.
I can't seem to locate the package(s) that cause this.

**Comment by razzeee** [comment]
But you didn't update the flatpak?

**Comment by cg00001** [comment]
> But you didn't update the flatpak?

Yes.

**Comment by cg00001** [comment]
Before doing that on the laptop, I did a full reinstall on all native packages on my desktop, hoping that it was my fault, but updating the laptop confirmed that something dependent to Kodi updated and caused these issues.

**Comment by cg00001** [comment]
Actually I was using a corrupted (possibly by me) folder, installing Titan MOD in a blank Kodi fixed the most important glitch for me, the Change thumbnail. Occasional crashes I can live with.
