### ISSUE TITLE
Kodi crashing few seconds after launch 

### ISSUE THREAD

**Issue by unicornsandcandies** [flathub/tv.kodi.Kodi#194]
Today I tried opening Kodi and I can't do anything for it to work. 

There's command output:
[terminal_output.txt](https://github.com/flathub/tv.kodi.Kodi/files/10252232/terminal_output.txt)

There's crashlog mentioned in output:
[crashlog.txt](https://github.com/flathub/tv.kodi.Kodi/files/10252234/crashlog.txt)

What can I do for this to work? It's on newest SteamOS, I never had a problem like this. I doubt it's a driver problem.

**Comment by razzeee** [comment]
Please try the beta branch, I'm unsure if the old version is even supposed to work on steamOS

**Comment by unicornsandcandies** [comment]
> Please try the beta branch, I'm unsure if the old version is even supposed to work on steamOS

I'm sorry but can you tell me how to switch to beta?

**Comment by razzeee** [comment]
https://discourse.flathub.org/t/how-to-use-flathub-beta/2111

**Comment by razzeee** [comment]
Should be fixed now.
