### ISSUE TITLE
PVR addons crash in Steam Deck.

### ISSUE THREAD

**Issue by Sanfe** [flathub/tv.kodi.Kodi#197]
I couldn't found a way to use IPTV simple addon. It crash when i tried to enable or install. Please, it's possible that the flatpak come with all dependencies needed? We are near that 2 millions of steam deck users now that we use flatpak so i'ts not enjoyable to add package outside flatpak because each new big release the OS dump this changes. Thanks

**Comment by razzeee** [comment]
Might be https://github.com/kodi-pvr/pvr.iptvsimple/issues/612

**Comment by razzeee** [comment]
Should be fixed now.
