### ISSUE TITLE
How can I use flatpak with Kodi 19.5

### ISSUE THREAD

**Issue by cg00001** [flathub/tv.kodi.Kodi#202]
I always seem to miss the exact details to use a previous version.
Assume I have nothing installed in my "flatpak list". Using Arch.
Thank you.

**Comment by razzeee** [comment]
https://github.com/flatpak/flatpak/issues/3097

**Comment by cg00001** [comment]
Thank you, easy enough:
```
sudo flatpak update --commit=e15d861c08f40a370b16efe0a999b59f85727032077f6c4bdc7102336387154d tv.kodi.Kodi
```

**Comment by cg00001** [comment]
For Arch Linux, Kodi v19.4 works best -Kodi v19.5 has too many glitches:
sudo flatpak update --commit=43be1f5599ab704cd79e6581b51040d5563e3f0025c2114e7e3751e2813b010e tv.kodi.Kodi
