### ISSUE TITLE
Error when using IPTV Simple addon

### ISSUE THREAD

**Issue by artempl** [flathub/tv.kodi.Kodi#206]
All streams are crashed with error on UI.
![Screenshot from 2023-02-01 15-35-26](https://user-images.githubusercontent.com/4968093/216044045-8add541d-0c32-4289-91c7-2b432532a8a9.png)

Error from logs:
`2023-02-01 15:30:24.413 T:123     error <general>: Unable to load /app/lib/kodi/addons/inputstream.ffmpegdirect/inputstream.ffmpegdirect.so.20.5.0, reason: libdav1d.so.5: cannot open shared object file: No such file or directory
`
If I enable using inputstream.adaptive in addon settings - it works fine for live streams, but cannot seek while watching EPG catchups in past.
![Screenshot from 2023-02-01 15-34-33](https://user-images.githubusercontent.com/4968093/216043829-e06cf9c8-ab15-4f06-bec3-2a1d3e2d888a.png)

**Comment by Erick555** [comment]
Kodi seems to ship own libdav1d but remove the [actual libraries](https://github.com/flathub/tv.kodi.Kodi/blob/master/modules/dav1d/dav1d.json#L11) after everything is build. This can't work. Moreover libdav1s is available in runtime so the proper fix here may be to remove libdav1d module from kodi and use runtime one instead.
