### ISSUE TITLE
PVR addons not available

### ISSUE THREAD

**Issue by p3ck** [flathub/tv.kodi.Kodi#215]
I know there was a patch to keep all the pvr addon's from being enabled by default on a fresh install.  But I'm unable to find any PVR addons and not able to activate the pvr addon for tvheadend.

Is there some magic that has to be done or is it not supported at all in flatpak now?

Thanks

**Comment by razzeee** [comment]
Seems to work fine for me. Not sure what's going on on your end.

**Comment by p3ck** [comment]
How can I debug this?  I don't even see a pvr directory in the addons

**Comment by razzeee** [comment]
In `addons` or in `my addons`?

**Comment by p3ck** [comment]
addons.  I also tried going via the pvr addon link...

![Screenshot from 2023-08-23 13-25-08](https://github.com/flathub/tv.kodi.Kodi/assets/2686136/2a7e762c-111e-4405-aa7f-cb08b508f712)

**Comment by p3ck** [comment]
[kodi.debug.log](https://github.com/flathub/tv.kodi.Kodi/files/12421858/kodi.debug.log)

I ran with debug and it does show that it sees the pvr plugins..  I just can't figure out how to get to them since they aren't in any menu...

**Comment by razzeee** [comment]
1. Click the cog on the homscreen
2. 2nd tile `Add-ons`
3. `My add-ons`
4. `PVR clients`
5. Find the client you want and enable it

**Comment by dajoho** [comment]
I can confirm this. The Flatpak version doesn't show any PVR clients in the addon repository, but if you go to Settings > Addons > My Addons (important) > PVR clients, the clients are already installed but just disabled. Once enabled they work fine.

Tested on both Fedora 37 and SteamDeck with the Nexus flatpak version.

I think this ticket can be closed.
