### ISSUE TITLE
LIRC and KODI

### ISSUE THREAD

**Issue by berni123** [flathub/tv.kodi.Kodi#217]
I have a working LIRC with an Hauppauge_350 remote, running under vdr, and created Lircmap.xml according to: https://kodi.wiki/view/HOW-TO:Set_up_LIRC
But it is not working with flathub kodi 19.2 oder 20.2 ...
Looking in tv.kodi.yml:
'# - modules/lirc/lirc.json
'# - -DENABLE_LIRCCLIENT=ON
has been commented out.

Why is lirc disabled? If it is disabled, can you reenable it please?
My lircd socket is avalable to anyone: srw-rw-rw- 1 root root 0 18. Sep 08:39 /var/run/lirc/lircd

Regards,
Bernd

**Comment by razzeee** [comment]
I would guess that's an oversight from https://github.com/flathub/tv.kodi.Kodi/commit/899d34823ed144a27a6ef406178bd57c8767106c

**Comment by berni123** [comment]
> I would guess that's an oversight from [899d348](https://github.com/flathub/tv.kodi.Kodi/commit/899d34823ed144a27a6ef406178bd57c8767106c)

Probably I am the only one in the world trying to use lirc with flathub/kodi ...

**Comment by razzeee** [comment]
I can prepare a test build later today

**Comment by berni123** [comment]
Well, hope you can fix it, because it would be nice to use kodi with a remote control connected via lirc

**Comment by berni123** [comment]
Is there any chance to patch the lirc package to get it running? Would love to run it with lirc and remote control ...

**Comment by razzeee** [comment]
You'll need to write a patch disabling systemd

**Comment by berni123** [comment]
Well I as the error in the build log is at "/usr/bin/mkdir: cannot create directory ‘/lib/systemd’: Read-only file system", I might think to "disable", you only have to remove it from the automake feature. So modify Makefile.am and configure.ac, rerun aclocal, autoconf, automake and the build process with ./configure, make, make install will run without systemd installation. 

vdr@vdr1:~/KODI/lirc-0.10.2_patched$ diff Makefile.am ../lirc-0.10.2/Makefile.am 
39,40c39,40
< ##AM_DISTCHECK_CONFIGURE_FLAGS = \
< ##    --with-systemdsystemunitdir=$${dc_install_base}/lib/systemd/system
---
> AM_DISTCHECK_CONFIGURE_FLAGS = \
>     --with-systemdsystemunitdir=$${dc_install_base}/lib/systemd/system
44,46c44,46
< ##if WITH_SYSTEMDSYSTEMUNITDIR
< ##    SYSTEMD_DIR         = systemd
< ##endif
---
> if WITH_SYSTEMDSYSTEMUNITDIR
>     SYSTEMD_DIR         = systemd
> endif

vdr@vdr1:~/KODI/lirc-0.10.2_patched$ diff configure.ac ../lirc-0.10.2/configure.ac 
210c210
< #AH_TEMPLATE([HAVE_SYSTEMD], [defined if systemd API is available])
---
> AH_TEMPLATE([HAVE_SYSTEMD], [defined if systemd API is available])
422,427c422,427
< #PKG_CHECK_MODULES([SYSTEMD],[libsystemd-daemon],,[true])
< #test -n "$SYSTEMD_LIBS" || PKG_CHECK_MODULES([SYSTEMD],[libsystemd],,[true])
< #if test -n "$SYSTEMD_LIBS"; then
< #  CFLAGS="$CFLAGS $SYSTEMD_CFLAGS"
< #  AC_DEFINE(HAVE_SYSTEMD)
< #fi
---
> PKG_CHECK_MODULES([SYSTEMD],[libsystemd-daemon],,[true])
> test -n "$SYSTEMD_LIBS" || PKG_CHECK_MODULES([SYSTEMD],[libsystemd],,[true])
> if test -n "$SYSTEMD_LIBS"; then
>   CFLAGS="$CFLAGS $SYSTEMD_CFLAGS"
>   AC_DEFINE(HAVE_SYSTEMD)
> fi
437,446c437,446
< #dnl Ubuntu's systemd pkg-config seems broken beyond repair. So:
< #kernelversion=`cat /proc/version || echo "non-linux"`
< #AS_CASE([$kernelversion],
< #  [*Ubuntu*],[
< #    AC_MSG_NOTICE([Hardwiring Ubuntu systemd setup])
< #    AC_SUBST([systemdsystemunitdir], [/lib/systemd/system])
< #    AM_CONDITIONAL([WITH_SYSTEMDSYSTEMUNITDIR], [true])
< #  ],[*],[
< #    SYSTEMD_SYSTEMUNITDIR
< #])
---
> dnl Ubuntu's systemd pkg-config seems broken beyond repair. So:
> kernelversion=`cat /proc/version || echo "non-linux"`
> AS_CASE([$kernelversion],
>   [*Ubuntu*],[
>     AC_MSG_NOTICE([Hardwiring Ubuntu systemd setup])
>     AC_SUBST([systemdsystemunitdir], [/lib/systemd/system])
>     AM_CONDITIONAL([WITH_SYSTEMDSYSTEMUNITDIR], [true])
>   ],[*],[
>     SYSTEMD_SYSTEMUNITDIR
> ])
528a529
>   systemd/Makefile

aclocal
autoconf
automake

... perhaps that helps ... 

Unfortunately I don't know how to patch this under flatpak to get it running with the three commands building the new autoconf files ...

**Comment by berni123** [comment]
Again: just trying to build kodi with flatpak-builder via make build and while compiling the build.log shows:
```shell
Building module lirc in /home/vdr/KODI/tv.kodi.Kodi/.flatpak-builder/build/lirc-1
========================================================================
checking for a BSD-compatible install... /usr/bin/install -c
```
but it automatically skips the make install in systemd section without any patching ... 
Perhaps this might be a hint too?

**Comment by ne20002** [comment]
I have the same problem. The remote is working with the ppa debian version. But now, as I need to switch to flatpack as of 20.3 because ppa is no longer supported ...
Is there any chance to get lirc working with the flatpak? Or is there another remote (available for buying) that is working and recommended?


This is the output of ir-keytable on my system:
```
/sys/class/rc/rc0/ gefunden mit:
	Name: Media Center Ed. eHome Infrared Remote Transceiver (0471:060d)
	Treiber mceusb
	Standardschlüsselcodeabbildung: rc-rc6-mce
	Eingabegerät: /dev/input/event4
	Linux-Infrarotfernbedienung : /dev/lirc0
	tangefügte BPF-Protokolle: Vorgang wird nicht unterstützt
	unterstützte Kernelprotokolle: lirc rc-5 rc-5-sz jvc sony nec sanyo mce_kbd rc-6 sharp xmp imon rc-mm 
	Aktivierte Kernelprotokolle: lirc rc-6 
	bus: 3, Anbieter/Produkt: 0471:060d, Version: 0x0101
	Wiederholungsverzögerung = 500 ms, Wiederholungsperiode = 125 ms
```

**Comment by berni123** [comment]
The problem is, that lirc does not compile in flatpack (see above), so there is no lirc at all until somebody who know who to write a  patch disabling systemd in lirc to compile it in flatpack.

**Comment by ne20002** [comment]
I don't think we need the complete Lirc in the flatpak. Usually the lirc receiver is installed on the host and Kodi just needs the
Lirc client.

**Comment by razzeee** [comment]
Can somebody check if https://github.com/flathub/tv.kodi.Kodi/pull/218#issuecomment-1894820348 does LIRC stuff?

**Comment by razzeee** [comment]
Can you try the lastest build?

**Comment by ne20002** [comment]
Ok, I installed latest build and it recognizes the remote.

By default only left, right, up and down key are working. 
I was able to assign a key from the remote as back key using keymap editor addon.
I was not able to do so for a number of other keys (Info, Enter, Menu).
Enter on the remote starts Celulloid, it works on my old installation (ppa).

Problems: 
* Keymap editor gives an error when saving as a normal user. I installed as system flatpak and it worked with the sudo user. 
* I need to check why it does not recognize the other keys on the remote. It may be an extra setting for mce remote on the system which is not available/seen in the flatpak.

**Comment by ne20002** [comment]
Is there a way on how to test if the flatpak sees the rc device? Maybe an included shell (as AddOn?)

**Comment by razzeee** [comment]
You can login to the shell that the flatpak runs in with `flatpak enter` if that helps

**Comment by ne20002** [comment]
@razzeee Thank you

I did a few test and I see the following:

`flatpak enter tv.kodi.Kodi ir-keytable` gives me the output as seen in the [above](https://github.com/flathub/tv.kodi.Kodi/issues/217#issuecomment-1890995833) comment.

`flatpak enter tv.kodi.Kodi ir-keytable -r` and `flatpak enter tv.kodi.Kodi ir-keytable -t` both gives a `/dev/input/event4: Permission denied`.

So I believe I have to add some permissions. How do I do that?

**Comment by razzeee** [comment]
Easiest way is to use https://flathub.org/apps/com.github.tchx84.Flatseal or kde settings if you are on kde (can't help with the later)

In theory I thought this should work, as we set `device=all`, there's also `device=input` now (it's new) but I don't think that should help here.

**Comment by ne20002** [comment]
I tried FlatSeal and dev=input is disabled. Even if I run it as root. I may do some more testing later ...

**Comment by razzeee** [comment]
> I tried FlatSeal and dev=input is disabled. Even if I run it as root.

You can enable it via flatseal, but need to restart the app then.

Running stuff as root, shouldn't change these afaik

**Comment by hfiguiere** [comment]
> In theory I thought this should work, as we set device=all, there's also device=input now (it's new) but I don't think that should help here.

There is no *stable* release of flatpak that support `device=input`.

Als don't confuse flatpak permision (expose the devices inside the flatpak) and system permissions (can I read/write the device). There is no way for the latter to be set by flatpak. In that case you should make sure the user running the flatpak is in the `input` group.

**Comment by hfiguiere** [comment]
I have to actual amend what I said: exposed devices INSIDE the sandbox have `nfsnobody` permissions and the user inside the sandbox belong to `nfsnobody`. 

So `--device=all` should work.

```
$ ls -l /dev/input/
total 0
drwxr-xr-x. 2 nfsnobody nfsnobody     60 Feb 11 16:17 by-id
drwxr-xr-x. 2 nfsnobody nfsnobody    220 Feb 11 16:17 by-path
crw-rw----. 1 nfsnobody nfsnobody 13, 64 Jan 27 00:05 event0
crw-rw----. 1 nfsnobody nfsnobody 13, 65 Jan 27 00:05 event1
crw-rw----. 1 nfsnobody nfsnobody 13, 74 Jan 27 00:05 event10
crw-rw----. 1 nfsnobody nfsnobody 13, 75 Jan 27 00:05 event11
[...]
$ id
uid=1000(hub) gid=1000(hub) groups=1000(hub),65534(nfsnobody)
```

**Comment by Erick555** [comment]
I don't think so - it would mean flatpak bypasses host file access protections. If you don't have access on host they you don't have it in flatpak.

**Comment by ne20002** [comment]
I will do a few more tests when I have time. I will also try to solve this on my host system.
As far as I see, I have two mappings: the ir-keytable mapping ir codes to keys and the Keymap in Lodi.
Changing the first to give the standard Kodi keys for actions should solve the problem. At least up, right, down, left are working, should  also be possible with others.

**Comment by hfiguiere** [comment]
Also

>  My lircd socket is avalable to anyone: srw-rw-rw- 1 root root 0 18. Sep 08:39 /var/run/lirc/lircd


This is not available inside the sandbox. `xdg-run/lirc` likely need to be added as a permission

**Comment by ne20002** [comment]
xdg-run seemed to help. I was able to change one key from remote with keymapeditor add-on.
But other buttons are still not regocnized by kodi. Also the socket /var/run/lirc/lircd is still not visible inside the sandbox.

**Comment by Erick555** [comment]
You need to add `--filesystem=/var/run/lirc` or `--filesystem=/run/lirc` if `/var/run` is symlink. xdg-run is for user subdir.

**Comment by ne20002** [comment]
> You need to add `--filesystem=/var/run/lirc` or `--filesystem=/run/lirc` if `/var/run` is symlink. xdg-run is for user subdir.

@Erick555 
And this fixed it. 👯 

My remote is now working fully with the Kodi flatpak. Thank you very much. 😃

**Comment by Erick555** [comment]
So kodi flatpak needs to add `--filesystem=/run/lirc` then this can be closed.
