### ISSUE TITLE
No input with GBM windowing

### ISSUE THREAD

**Issue by toupeira** [flathub/tv.kodi.Kodi#228]
When running Kodi in a TTY using the GBM windowing system, keyboard input doesn't work even though:

- The Flatpak uses `--device=all` (and forcing it with `flatpak run --device=all tv.kodi.Kodi` makes no difference)
- I'm a member of the `input` group (verified with `groups`), and the devices in `/dev/input` are writable by the `input` group.

Running the Debian package with GBM works fine, so I'm wondering if this is a limitation of Flatpak, or some other setup is needed?

Note that Kodi can still be killed by pressing Ctrl+C, but I think that's just a standard signal handler from the TTY.

Versions:
- Debian unstable
- Kodi Flatpak 20.3-Nexus
- Flatpak 1.14.5-1+b2

**Comment by razzeee** [comment]
> Running the Debian package with GBM works fine, so I'm wondering if this is a limitation of Flatpak, or some other setup is needed?

I guess running some other flatpaks might help you figure that out?

**Comment by toupeira** [comment]
Oh good call :) I knew MPV supports GBM, so I tried that and input works fine there!

Looking at the [manifest](https://github.com/flathub/io.mpv.Mpv/blob/master/io.mpv.Mpv.yml) nothing stands out, I tried adding the `--filesystem=host:ro` and `--socket=x11` arguments with Kodi but that didn't make a difference.

I enabled Kodi's debug log and found this:

```
debug <general>: libinput: event2  - skip unconfigured input device '/dev/input/event2'
debug <general>: libinput: event4  - skip unconfigured input device '/dev/input/event4'
debug <general>: libinput: event1  - skip unconfigured input device '/dev/input/event1'
debug <general>: libinput: event0  - skip unconfigured input device '/dev/input/event0'
debug <general>: libinput: event3  - skip unconfigured input device '/dev/input/event3'
debug <general>: libinput: event6  - skip unconfigured input device '/dev/input/event6'
debug <general>: libinput: event7  - skip unconfigured input device '/dev/input/event7'
debug <general>: libinput: event8  - skip unconfigured input device '/dev/input/event8'
debug <general>: libinput: event9  - skip unconfigured input device '/dev/input/event9'
debug <general>: libinput: event5  - skip unconfigured input device '/dev/input/event5'
```

My keyboard is `/dev/input/event3` and connected over USB, so apparently it's skipping it for some reason.

Searching for the error brought me to https://gitlab.freedesktop.org/libinput/libinput/-/commit/23d543b711cf027df3f7322e5dc51d352ed6179c and https://github.com/flatpak/flatpak/issues/961.

I don't really understand the details here, but it seems Kodi is using `udev` to handle inputs which doesn't work in Flatpak, and MPV might be using some other method?

Let me know if you want me to open an issue on Kodi's tracker as well.

**Comment by Ra72xx** [comment]
Anything I can do to help here? Switching from Kodi native packages to flatpak and also ran into this with no previous flatpak experience.

**Comment by Ra72xx** [comment]
Replying to myself: Starting the Kodi fflatpak with this command line
```
/usr/bin/flatpak run --filesystem=/run/udev:ro --branch=stable --arch=x86_64 --command=kodi tv.kodi.Kodi --standalone --windowing=gbm 
```
makes input devices available (the "--filesystem" part is relevant). However, only the devices available at Kodi startup, no later hotplugs.

**Comment by toupeira** [comment]
@Ra72xx thanks, this works for me too! :+1: 

Now my next hurdle is that VT switching doesn't seem to be implemented yet, I see that's mentioned in https://github.com/xbmc/xbmc/issues/14876.

**Comment by Ra72xx** [comment]
For the hotplug problem, I currently try out https://github.com/aiberia/persistent-evdev
Creating persistent /dev-entries for the devices meant to control kodi BEFORE starting Kodi flatpak seems to work for me.

**Comment by Ludo444** [comment]
Same issue here on Debian 12, no luck with above workaround command.

**Comment by Ludo444** [comment]
@toupeira thanks! that helped
