### ISSUE TITLE
Please update tv.kodi.Kodi to use the 23.08 runtime

### ISSUE THREAD

**Issue by LaurentBonnaud** [flathub/tv.kodi.Kodi#255]
Hi,
tv.kodi.Kodi depends on the 22.08 runtime:
```
$ flatpak info tv.kodi.Kodi
[...]
     Runtime: org.freedesktop.Platform/x86_64/22.08
```
Would it be possible to update it to the 23.08 runtime?

**Comment by razzeee** [comment]
Certainly is, but it's not as easy as I would like it to be. See the PRs here to see three approaches

**Comment by Erick555** [comment]
Here's something that [builds](https://github.com/flathub/tv.kodi.Kodi/pull/225#issuecomment-2118370157)

**Comment by LaurentBonnaud** [comment]
Thanks for this build!
I tested this build, which is more recent:
`flatpak install --user https://dl.flathub.org/build-repo/104909/tv.kodi.Kodi.flatpakref`
It seems to work fine on my system.
I am just seeing an error message immediately after launch:
```
$ flatpak run tv.kodi.Kodi
'this->recurse > 0' failed at ../src/pipewire/thread-loop.c:63 do_unlock()
```

**Comment by razzeee** [comment]
Might be due to the not exposed pipewire socket - you need to add that via flatseal if you want it

**Comment by LaurentBonnaud** [comment]
Thank you for the fix!
Do you know when the build will appear in flathub?

**Comment by razzeee** [comment]
It should be there, or show up shortly
