### ISSUE TITLE
error: Could not connect: No such file or directory

### ISSUE THREAD

**Issue by falling** [flathub/tv.kodi.Kodi#269]
root@Z4Pro-KT8L:/# flatpak -v  run  tv.kodi.Kodi
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /root/.local/share/flatpak
F: Opening user flatpak installation at path /root/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
**error**: Could not connect: No such file or directory

root@Z4Pro-KT8L:/# cat /etc/os-release
PRETTY_NAME="Ubuntu 24.04 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo

**Comment by razzeee** [comment]
Does flatpak work at all for you?

**Comment by falling** [comment]
it's working with this command before start ,thank you!
> dbus-daemon --system
