### ISSUE TITLE
update checksum error 

### ISSUE THREAD

**Issue by C-O-D** [flathub/tv.kodi.Kodi#305]
I'm getting an error when trying to update the app:

opcode close: Corrupted file object; checksum expected='c0273e4cad8f3047a5bf07c2a2c19f440eb994e3bc50adbd240a5126df75b470' actual='c64818280418936813ed65db6e553a4f22f01029b99e6510e40d98ef8a525b3b'

**Comment by razzeee** [comment]
updated just fine for me, try `flatpak repair` on your install

**Comment by C-O-D** [comment]
Thanks, that did it!
