### ISSUE TITLE
Update runtime to 24.08

### ISSUE THREAD

**Issue by chcore** [flathub/tv.kodi.Kodi#308]
The 24.08 runtime includes a long-awaited fix for correctly playing interlaced content on intel systems. Would it be possible to update this project to use it?

Thanks

**Comment by razzeee** [comment]
Are you able to test https://github.com/flathub/tv.kodi.Kodi/pull/309#issuecomment-2541294926 ?

**Comment by chcore** [comment]
It fails to launch for me, with this error:

`/app/lib/kodi/kodi.bin: error while loading shared libraries: libmsrpc3-samba4.so: cannot open shared object file: No such file or directory`

I assume it is talking about a `libmsrpc3-samba4.so` within the flatpak runtime?

**Comment by Erick555** [comment]
There is no such thing in the runtime

**Comment by chcore** [comment]
https://github.com/flathub/tv.kodi.Kodi/pull/309#issuecomment-2544499047 looks good to me!
