### ISSUE TITLE
[Kodi crashes] addon installation

### ISSUE THREAD

**Issue by achimfrase** [flathub/tv.kodi.Kodi#36]
Kodi 18.0rc5.2-Leia crashes if I try to install any addon. Regardless which addon.
If I select an addon and press enter I don't get to the point where I can click "install".
I also tried to remove the configuration directory ".var/app/tv.kodi.Kodi", but that didn't help.

**Comment by wsnipex** [comment]
indeed, I can reproduce.
>terminate called after throwing an instance of 'fmt::v5::format_error'

likely due to the libfmt bump in https://github.com/flathub/tv.kodi.Kodi/pull/34
although https://github.com/xbmc/xbmc/commit/2e77047ed1788dd912cea242f79b0e82bb750704 should fix that...
@tilosp ping
