### ISSUE TITLE
Can't use external hard disk as Media Source

### ISSUE THREAD

**Issue by bastianilso** [flathub/tv.kodi.Kodi#46]
Hi,

I want to Kodi to use my external hard drive mounted at "/run/media/bastianilso/harddrive" as media source, but it seems that this path is not accessible from the Flatpak.

- What is the right way to address this issue in the long run? Does Kodi need to implement a portal here? Or is it on the Flatpak manifest permission side of things?

- is there a temporary Flatpak CLI command workaround that can be used to make my external harddrive accessible (punching a hole in the sandbox) for now?

**Comment by bastianilso** [comment]
I believe this is also related to fx:
https://github.com/flathub/org.videolan.VLC/issues/8

**Comment by bastianilso** [comment]
Also related:
https://github.com/flathub/com.valvesoftware.Steam/issues/55

> is there a temporary Flatpak CLI command workaround that can be used to make my external harddrive accessible (punching a hole in the sandbox) for now?

I found an answer to this now.
`flatpak override --user --filesystem=/path/to/your/harddisk/ tv.kodi.Kodi`

**Comment by Marko10-000** [comment]
Yes, that's the current only solution that exists. Perhaps we should communicate that more clearly (see #47)
