### ISSUE TITLE
Websockets are not supported in flatpak.

### ISSUE THREAD

**Issue by lukasmrtvy** [flathub/tv.kodi.Kodi#51]
Seems that websockets are not supported in flatpak.
`Allow remote control from applications on this system` in Settings/Service can be enabled, but there is no `Allow remote control from applications on other systems` (Which allows websockets afaik) is missing from GUI.

but there is listening TCP process -> 0.0.0.0:9090 (0.0.0.0:8080 too)

Example of GUI options:
https://kodi.wiki/view/File:Services_control2.JPG

EDIT:
seems that I disabled it with:
```
printf "<advancedsettings>\n    <services>\n        <esallinterfaces>true</esallinterfaces>\n        <webserver>true</webserver>\n        <zeroconf>true</zeroconf>\n    </services>\n</advancedsettings>" > /home/kodi/.var/app/tv.kodi.Kodi/data/userdata/advancedsettings.xml
```
according to this: https://kodi.wiki/view/Web_interface

**Comment by lukasmrtvy** [comment]
My mistake, seems that is not possible to enable websockets and webserver with advancedsettings.xml

**Comment by parkerlreed** [comment]
Does the web server just NOT WORK for Flatpak? I get nothing on 8080 visiting from other machines (No firewall for LAN)

**Comment by parkerlreed** [comment]
Heads up for anyone else bashing their head against this. Steam has a service on 8080 by default...

**Comment by parkerlreed** [comment]
Steam CEF debugging is the culprit

**Comment by boeremak** [comment]
> Heads up for anyone else bashing their head against this. Steam has a service on 8080 by default...

Just ran into this on Bazzite....... Thanks.
