### ISSUE TITLE
Kodi Desktop Session

### ISSUE THREAD

**Issue by alexhaydock** [flathub/tv.kodi.Kodi#59]
Is it possible for a Flatpak application such as Kodi to provide the Kodi desktop session that can usually be accessed from the login screen / desktop manager?

I notice it does not currently and if the feature is available then I can't work out how to enable it, but I'm wondering whether it's an issue with the fundamental architecture of Flatpak that means this isn't possible. I notice that the Steam Flatpak does not enable this either (although admittedly this usually also requires `steamos-desktop` in addition to the regular package) which is what makes me think that possibly this is the case.

**Comment by wsnipex** [comment]
It's already there: /var/lib/flatpak/app/tv.kodi.Kodi/current/active/export/share/applications/tv.kodi.Kodi.desktop

My ubuntu/XCFE desktop shows it automatically under the Multimedia category

**Comment by alexhaydock** [comment]
> edit2: just symlink /var/lib/flatpak/app/tv.kodi.Kodi/current/active/export/share/applications/tv.kodi.Kodi.desktop to /usr/share/xsessions/

Fantastic. Yes this is what I meant, thanks! :+1:

For anyone else finding this issue at a later date:

```sh
ln -sf /var/lib/flatpak/app/tv.kodi.Kodi/current/active/export/share/applications/tv.kodi.Kodi.desktop /usr/share/xsessions/kodi
```

ought to do it.
