### ISSUE TITLE
Kodi crash

### ISSUE THREAD

**Issue by Nanco300** [flathub/tv.kodi.Kodi#60]
When I run Kodi this error appears in terminal:

/app/bin/kodi: line 220:    10 Killed                  ${KODI_BINARY} $SAVED_ARGS

Flatpak version: 1.0.8-0ubuntu0.18.04.1

Ref: app/tv.kodi.Kodi/x86_64/stable
ID: tv.kodi.Kodi
Arch: x86_64
Branch: stable
Collection ID: org.flathub.Stable
Date: 2019-05-29 20:06:12 +0000
Subject: Use a link that actually works. (de9409a3)
Commit: a2b10624e2f68df53f2266ff3e9f41c9a5aad0350aadd088f7d2c2d5b424b7a8
Parent: 27dfd62f6350b1fdf78d0c2b32eba55a9ce55f8fc116dca831aab2dbf2ba0d77
Download size: 130,9 MB
Installed size: 300,1 MB
Runtime: org.freedesktop.Platform/x86_64/18.08
Sdk: org.freedesktop.Sdk/x86_64/18.08

**Comment by Marko10-000** [comment]
Can you check it again? Today I had a similar bug with Steam because I didn't have the current libraries of my graphics driver (Nividia).

**Comment by Marko10-000** [comment]
No response.
