### ISSUE TITLE
Kodi file manager

### ISSUE THREAD

**Issue by cmatomic** [flathub/tv.kodi.Kodi#63]
Kodi faltpak doesn't give me access to all directories in / home directory .

**Comment by Erick555** [comment]
This is intentional and the point of sandboxing. You may use `flatpak override --filesystem=home tv.kodi.Kodi` to chnage that locally.

**Comment by cmatomic** [comment]
thanks with this option we can only select one folder

**Comment by nicrame** [comment]
This will give You access to all /home folders:
flatpak override --filesystem=/home tv.kodi.Kodi
But Linux user must also have access to all those folders.

**Comment by vilmasvensson** [comment]
Could we close this issue as it isn't an issue, but a feature?
