### ISSUE TITLE
Update runtime to 19.08

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/tv.kodi.Kodi#67]

**Comment by Erick555** [comment]
This depends on [org.freedesktop.Sdk.Extension.openjdk11](org.freedesktop.Sdk.Extension.openjdk11) having branch for 19.08. [shared-modules/udev/udev-175.json](https://github.com/flathub/tv.kodi.Kodi/blob/master/tv.kodi.Kodi.yml#L30) can be dropped fro manifest as libudev is in runtime now.

**Comment by mbooth101** [comment]
FWIW, openjdk11 is now available for freedesktop 19.08.
