### ISSUE TITLE
Does kodi *really* depend on Java?

### ISSUE THREAD

**Issue by mbooth101** [flathub/tv.kodi.Kodi#70]
Kodi specifies a requirement on the openjdk11 extension:

https://github.com/flathub/tv.kodi.Kodi/blob/master/tv.kodi.Kodi.yml#L6

But then tries to use openjdk10: 

https://github.com/flathub/tv.kodi.Kodi/blob/master/tv.kodi.Kodi.yml#L66 &
https://github.com/flathub/tv.kodi.Kodi/blob/master/tv.kodi.Kodi.yml#L106

Which cannot possibly work because the openjdk11 extension does not provide this openjdk10 path!

Furthermore, at no point is the openjdk11 ```install.sh``` script called, so the Kodi app is not even shipping with a Java runtime. This means that even if Kodo did actually ship some bytecode, there's no way it can be executed...

Are you sure Kodi actually requires Java? Or something silently failing during build and silently missing at runtime?

**Comment by Erick555** [comment]
@mbooth101 the openjdk 10 vs 11 is a bug which breaks the build: https://flathub.org/builds/#/builders/32/builds/9456 . There are PRs fixing it. How it once worked remains mystery for us :smile:

**Comment by mbooth101** [comment]
Interesting, is there some Java-based build utility that is not needed at runtime? I wonder if it builds successfully without Java at all!

**Comment by Erick555** [comment]
I don't know however looking at my distro package it needs openjdk only at build time.

**Comment by wsnipex** [comment]
Yes, we only need java (actually groovy) at build time. It's used by swig to generate some code.

**Comment by mbooth101** [comment]
@wsnipex Aha, thanks for the clarification -- I guess you should feel free to close this when #61 is merged.
