### ISSUE TITLE
Using a remote control

### ISSUE THREAD

**Issue by Toniob** [flathub/tv.kodi.Kodi#74]
Hi,

I've got a MCE remote control. Is there a way to make it work with the flatpak version of kodi ?

Thanks

**Comment by bam80** [comment]
Hi, yes default keymap already has mapping for MCE, see the [keyboard..xml](https://github.com/xbmc/xbmc/blob/master/system/keymaps/keyboard.xml) files included:
https://kodi.wiki/view/Keymap#Defaults

**Comment by Toniob** [comment]
So it should work out of the box ?
I used the debian packaged version of kodi (v17), with lirc and it did work.

I recently switched to the flatpak version of kodi. The remote control does nothing neither with or without lirc started.

**Comment by bam80** [comment]
Please try to understand what kind of MCE remote do you have:
https://kodi.wiki/view/MCE_remote_controls
https://kodi.wiki/view/List_of_MCE_remote_controls

I recommend setup without Lirc.

**Comment by bam80** [comment]
If you have remote which doesn't send keyboard keystrokes (RC6 or eHome remotes), try to get scancodes with `ir-keytable` (no need to use inputlirc or lircd):
https://kodi.wiki/view/HOW-TO:Set_up_an_MCE_remote_control_in_Linux#Edit_the_driver_table

**Comment by Toniob** [comment]
Hi,

I've got `ir-keytable` to work. It seems ok when I try the configuration (with `ir-keytable -t`). Every key outputs something. But in Kodi, nothing happens. Did I miss something ?

**Comment by bam80** [comment]
Hello, good start.
Have you made sure no lircd or other *lirc services run?
Let's first achieve your remote works as keyboard in host OS.
Try to map some usual keys (e.g arrows) and make sure they work in usual programs.
