### ISSUE TITLE
Matrix?

### ISSUE THREAD

**Issue by bam80** [flathub/tv.kodi.Kodi#76]
Hi, has anyone tried to port it to Matrix already?

**Comment by Marko10-000** [comment]
Nop, I would start working on it when the first release candidate is published (did I miss something?).

Can I ask you why you are asking? Are you interested in dev builds?

**Comment by Razzeee** [comment]
Personally I would like to have dev builds, as we do nightlies for android, ios, darwin and windows (http://mirrors.kodi.tv/nightlies/) but I always felt it might be cool to also have linux.

Still it would probably cause considerable overhead and most people on linux might be able to build on their own.

**Comment by Marko10-000** [comment]
Personally I think it would be no problem to create the scripts, but on the other hand I don't want to spam the build servers with ~2h builds if I don't pay for them.

What could be done is to create a branch that won't be built, but everyone can just run the build for themselves. There was once an announcement that somehow a dev branch will be built as well. @nedrichards could you say more about this (especially about the part of the branch that is not built)? I don't want to overload your infrastructure.

**Comment by Razzeee** [comment]
Can't we time the builds? So create one each week or night.

**Comment by bam80** [comment]
> Can I ask you why you are asking? Are you interested in dev builds?

Yes. Nightlies supported officially for mainstream distros only. It's happened to be I don't run one of these :)

> Personally I think it would be no problem to create the scripts, but on the other hand I don't want to spam the build servers with ~2h builds if I don't pay for them.

The  builds are reduplicated by space, aren't they? Not sure if they rebuild quicker on minor changes..

**Comment by tilosp** [comment]
> The builds are reduplicated by space, aren't they? Not sure if they rebuild quicker on minor changes..

duplicated files get de-duplicated by flatpak, but the build on flathub will always take the same time

> Personally I would like to have dev builds, as we do nightlies for android, ios, darwin and windows (http://mirrors.kodi.tv/nightlies/) but I always felt it might be cool to also have linux.

I think this could be achieved by also building flatpaks on https://jenkins.kodi.tv where the other nightlies get build.

**Comment by bam80** [comment]
> I would start working on it when the first release candidate is published

Probably the building part won't change so we could start already without concerns of redoing work

**Comment by bam80** [comment]
FYI: the bugfix to Matrix is out, and I troubling to test it due lack of support of Matrix in Flatpak:
https://github.com/xbmc/xbmc/issues/17324#issuecomment-583760730

**Comment by bam80** [comment]
> Can't we time the builds? So create one each week or night.

Another option: Kodi team members could trigger the builds.

**Comment by RyuzakiKK** [comment]
I opened a PR for Matrix here https://github.com/flathub/tv.kodi.Kodi/pull/93

**Comment by Marko10-000** [comment]
@bam80 I merged the changes from @RyuzakiKK into the `beta` branch. You should be able to install it from the flathub beta repository.

How to install:
```sh
flatpak remote-add --if-not-exists flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo &&
flatpak install --reinstall flathub-beta tv.kodi.Kodi//beta
```
Add `--user` to both commands when you want to install it not system wide but only on your locale user. Btw. it current starts up only in wayland mode (not with x11). That's a bug that we have to fix. You can run it in X11-mode by starting inside of the flatpak `/app/lib/kodi/kodi-x11`.
