### ISSUE TITLE
Kodi Crashes on Wayland but Runs Fine on X11

### ISSUE THREAD

**Issue by Saroufim** [flathub/tv.kodi.Kodi#78]
When running Kodi under GNOME Wayland, it crashes before even starting up with the following error:
```
libva info: VA-API version 1.5.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/nouveau_drv_video.so
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/intel-vaapi-driver/nouveau_drv_video.so
libva info: Trying to open /usr/lib/x86_64-linux-gnu/GL/lib/dri/nouveau_drv_video.so
libva info: Found init function __vaDriverInit_1_5
libva info: va_openDriver() returns 0
terminate called after throwing an instance of 'std::system_error'
  what():  wl_display_dispatch_pending: Protocol error

```
However, when launched through X11, it runs perfectly fine.

**Comment by wsnipex** [comment]
please try with v19

**Comment by Saroufim** [comment]
Has this been pushed out yet? I'm still on 18.8

**Comment by wsnipex** [comment]
$ flatpak info tv.kodi.Kodi 

> Kodi - Media center
          ID: tv.kodi.Kodi
         Ref: app/tv.kodi.Kodi/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 19.0-Matrix
     License: GPL-2.0-only GPL-2.0-or-later LGPL-2.1-or-later MIT BSD-3-Clause BSD-4-Clause
      Origin: flathub-1
  Collection: org.flathub.Stable
Installation: user
   Installed: 263,8 MB
     Runtime: org.freedesktop.Platform/x86_64/20.08
         Sdk: org.freedesktop.Sdk/x86_64/20.08
      Commit: 25201d2c07321968e3eef04a205c366750f4e9fe9a86c95a7bd870dbec81b157
      Parent: 75a8cbf685c9d1c1b35e30853f45a7590bc8882404bb44888efb5bc21f51aabc
     Subject: Enable GnuTLS in FFmpeg (d3cb0457)
        Date: 2021-03-05 08:42:31 +0000


did you try
> flatpak update tv.kodi.Kodi

**Comment by Saroufim** [comment]
I just got the update now. I'll report back as soon as it's done.

**Comment by Saroufim** [comment]
It works but after freezing 20-30 seconds on startup

**Comment by vilmasvensson** [comment]
Could you provide some logs?

**Comment by Saroufim** [comment]
I think the issue was with updating the addons because after the first run, it ran just fine and I can no longer reproduce the issue

**Comment by vilmasvensson** [comment]
Thank you, can you close the issue?
