### ISSUE TITLE
Flathub using older version 18-5

### ISSUE THREAD

**Issue by ukbeast** [flathub/tv.kodi.Kodi#84]
I notice the repository was updated to 18-6 on git, but flathub is still using version 18-5 from November last year. 
https://flathub.org/apps/details/tv.kodi.Kodi

**Comment by Erick555** [comment]
The app itself is on 18-6 (you can confirm this while launching it), it's just metadata that wasn't updated: https://github.com/flathub/tv.kodi.Kodi/blob/master/tv.kodi.Kodi.appdata.xml#L41

**Comment by Erick555** [comment]
https://github.com/flathub/tv.kodi.Kodi/pull/85 should fix this.
