### ISSUE TITLE
KODI crash when using web interface control (Chorus)

### ISSUE THREAD

**Issue by nicrame** [flathub/tv.kodi.Kodi#90]
Most of the time, when i'm trying to use Chorus (web interface for controlling and interacting with Kodi) and try to access Movies KODI crashes.
I enabled logging of components: libCURL, JSON-RPC, Announcer, WWW server, Database. But LOG says nothing about crash.
It happen when i enter "Movies", website is loaded but there is info down-right "web socket connection lost".
Web GUI when connection is lost:
![Zrzut ekranu (51)](https://user-images.githubusercontent.com/5872054/92999304-1b0fcb80-f520-11ea-87b0-a33dca2c4100.png)
kodi log:
https://pastebin.pl/view/raw/88332661
kodi_crashlog-20200912_162848:
https://pastebin.pl/view/raw/7060c005

There is also large file generated core.kodi-x11.1001.66ab4a28af424498894aa0df942abaaa.52211.1599920925000000.lz4:
https://love.itos.pl/s/PJFW67jXmBEgwFT

**Comment by I-Cat** [comment]
I broke it

**Comment by nicrame** [comment]
It is working fine now on v19.
