### ISSUE TITLE
X11 version of Kodi isn't started automatically

### ISSUE THREAD

**Issue by Marko10-000** [flathub/tv.kodi.Kodi#94]
The start script doesn't check if a Wayland environment is available to automatically starts the X11 version. @wsnipex wasn't this originally supported by Kodi?

**Comment by wsnipex** [comment]
Please see https://github.com/xbmc/xbmc/pull/18534

TLDR: Kodi now supports all windowing systems in a single binary, so the build steps need to be adjusted.

**Comment by wsnipex** [comment]
should be fixed with #95
